waypoints:
- name: sofa
  x: 0.178
  y: 1.722
  yaw: 0.0
- name: entrance
  x: 0.525
  y: -0.038
  yaw: 1.381
- name: window
  x: -0.665
  y: 0.012
  yaw: 3.14
- name: charging
  x: 0.0
  y: 0.0
  yaw: 0.0
loop: true
waypoint_delay_sec: 5.0
loop_delay_sec: 30.0
max_goal_retries: 3
goal_retry_delay_sec: 5.0
