-- pgvector 를 켜지 않습니다. (S15P11E102-218)
--
-- 이 파일에는 `CREATE EXTENSION IF NOT EXISTS vector;` 가 있었습니다. 지웠습니다.
--
-- 왜 (실측)
--   Upstage solar-embedding-1-large 의 출력은 4096차원입니다. pgvector 0.8.5 가
--   인덱싱할 수 있는 상한은 vector 2,000 / halfvec 4,000 차원입니다. 즉 4096차원은
--   halfvec 으로도 인덱스를 만들 수 없고, 남는 선택지는 인덱스 없는 순차 스캔뿐입니다.
--   한국어 품질 때문에 Upstage 를 포기할 수 없다는 판단이라, 의미 검색을 외부 벡터
--   스토어(Qdrant)로 옮겼습니다. infra/compose.prod.yml 의 qdrant 서비스를 보세요.
--
-- 왜 파일을 지우지 않고 남겨 두는가
--   1. compose 가 이 디렉터리를 마운트합니다(`./docker/postgres/init:...:ro`).
--      디렉터리가 비면 git 이 추적하지 않아서 체크아웃한 곳에 경로가 없습니다.
--   2. 다음 사람이 "왜 pgvector 이미지를 쓰면서 확장을 안 켜지?"의 답을 여기서 찾습니다.
--      기록이 없으면 누군가 친절하게 다시 켤 것이고, 그때부터 검색 경로가 둘이 됩니다.
--
-- 이미지는 여전히 pgvector/pgvector 입니다
--   운영 중 PostgreSQL 메이저 버전이나 이미지를 바꾸는 것이 확장 하나보다 위험합니다
--   (infra/README.md §9). 확장 바이너리가 이미지에 들어 있을 뿐, 활성화되지 않습니다.
--   `FlywayMigrationValidationTest.pgvectorIsNotUsed` 가 이 사실을 능동적으로 검증합니다.
